### ISSUE TITLE
Remove underlining

### ISSUE THREAD

**Issue by tsawitzki** [slim-template/language-slim#15]
Hello, I get an underlining of every abstracted HTML-Element when I activate the Syntax-Highlighting. Is it meant to be like this? Otherwise: Any idea where this may come from? There are now settings for this. It really does not help the view imo …

**Comment by jessejanderson** [comment]
Getting the same thing - it's incredibly distracting. Not feeling very encouraged that no one has replied to this 6 month old comment...

**Comment by vemv** [comment]
Might be just me, but is underlining actually broken?

Note the trailing underscored area:

![image](https://cloud.githubusercontent.com/assets/1162994/19220372/222cb572-8e2c-11e6-9208-767a1a8a577e.png)

**Comment by aeyoa** [comment]
I found the workaround for this annoying issue.

Open your custom styles

<img width="292" alt="screen shot 2017-04-21 at 01 02 08" src="https://cloud.githubusercontent.com/assets/6937970/25254437/37b17596-262e-11e7-8f3b-b2080ea365bc.png">

And add the following rules 
```less
atom-pane[data-active-item-name="item.html.slim"] {
  .syntax--entity.syntax--name.syntax--tag {
    text-decoration: none;
  }
}
```

This should hide the underlining.
